### ISSUE TITLE
Updated colour scheme for interface

### ISSUE THREAD

**Issue by rwoodpecker** [ludios/grab-site#12]
I realise this is pretty trivial - but the brown background colour looks pretty dated and is a bit boring. Would there be any interest in lightening these up a bit to look a bit more modern?

**Comment by ivan** [comment]
Yeah, I think so.  I would want to do support for multiple styles via a URL parameter.  Modern-light, my beloved brown, and possibly a dark theme.  (yipdw already has colors for one.)

**Comment by 12As** [comment]
Now that gs-server can serve arbitrary URLs, maybe the dashboard should be broken into html, js, and css files.  That way, if someone wanted to change the dashboard page or CSS, they could just put a properly named file in the CWD of grab-site and it would serve that instead of the default.  This would allow color changes and other customization.

**Comment by ivan** [comment]
A little while back, I tried many lighter background colors, but they were harder to look at.  If someone wants to do something particularly good and add support for multiple styles, I would probably take the PR.
