### ISSUE TITLE
Error installing on MacOS 10.13.4 High Sierra 

### ISSUE THREAD

**Issue by EtienneBerlin** [ludios/grab-site#121]
when installing i get the error "Could not find a version that satisfies the requirement click>=6.3" like this:

```
theMatrix-3:~ etienne$ pyvenv-3.4 ~/gs-venv
theMatrix-3:~ etienne$ ~/gs-venv/bin/pip3 install git+https://github.com/ludios/grab-site
Collecting git+https://github.com/ludios/grab-site
  Cloning https://github.com/ludios/grab-site to /var/folders/fd/rfs9d9ys5qg7kc3ks6gljt1m0000gn/T/pip-oi37ho43-build
Collecting click>=6.3 (from grab-site==1.6.0)
  Could not find a version that satisfies the requirement click>=6.3 (from grab-site==1.6.0) (from versions: )
No matching distribution found for click>=6.3 (from grab-site==1.6.0)
```

Xcode and Python 3.4. are installed and working.

any idea would be much appreciated. thanks.

**Comment by ivan** [comment]
I believe this is a problem caused by pypi disabling support for anything older than TLS 1.2: https://github.com/pypa/packaging-problems/issues/134#issuecomment-378312672. The macOS Python 3.4 installer uses an older OpenSSL that does not support TLS 1.2.

Unfortunately, I do not have a macOS machine right now to test fixes to the macOS install steps, but if you would like to experiment, I believe Homebrew has a newer OpenSSL that might work.

If you would like to try Homebrew, I would be interested to know whether this works:

First, uninstall/remove the existing Python 3.4 and 

```
rm -rf ~/gs-venv
```

then install Homebrew and

```bash
brew update
brew install pyenv
pyenv install 3.4.7
~/.pyenv/versions/3.4.7/bin/pyvenv-3.4 ~/gs-venv
~/gs-venv/bin/pip3 install git+https://github.com/ludios/grab-site
```

**Comment by ivan** [comment]
I updated and tested the new install steps on https://github.com/ludios/grab-site#install-on-macos, please let me know if you have any problems.

**Comment by EtienneBerlin** [comment]
hi ivan,

i tested the new install instructions and they work just fine - thanks for your quick help.

only thing that comes up now is this note: 
```
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
etienne

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Am Di. 15.05.2018 um 23:00h schrieb Ivan Kozik:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

> I updated and tested the new install steps on https://github.com/ludios/grab-site#install-on-macos, please let me know if you have any problems.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--


↓

BAR PACIFICO/ 
GESTALTUNG UND PROZESSE 

Girardet & Hickethier GbR
Oranienstraße 188 · 10999 Berlin
(030) 60 98 69 08

www.bar-pacifico.de

**Comment by ivan** [comment]
Good to hear.

That pip warning can be ignored.
