### ISSUE TITLE
Missing linked files.

### ISSUE THREAD

**Issue by ZizzyDizzyMC** [ludios/grab-site#125]
I've done some testing and apparently grab-site just completely misses files for some reason on this site:
`grab-site https://www.mlptf2mods.com/mods/all-class_hats/the_adorable_accolade --delay=1000-3000 --concurrency=2 --no-offsite-links --igon --1`

It misses the download link, completely and silently never catches it.  Not sure where to go from here except make an issue and see if someone else can figure it out.

**Comment by ZizzyDizzyMC** [comment]
It misses the zip on my install, not sure what I can do.  I have done `gs-dump-urls DIR/wpull.db done | grep zip` and got nothing.

**Comment by ivan** [comment]
Ah, sorry, I missed that `--no-offsite-links`, which also prevents the grabbing of that .zip file because it's on a different domain (subdomain).  It should work with just:

```
grab-site https://www.mlptf2mods.com/mods/all-class_hats/the_adorable_accolade --delay=1000-3000 --concurrency=2 --igon
```

**Comment by ZizzyDizzyMC** [comment]
That's a little strange, considering using `--no-offsite-links` allows it to grab a `.jpg` file from `subdomain.domain.com`  If you had already run a test run using my command with `--no-offsite-links` check to see that `.jpg` with `gs-dump-urls DIR/wpull.db done | grep dash` 

Is this accidental un-wanted behavior?

Also: Is there a way to limit grab-site to *.domain.com (maybe should open up new issue / request if not)

**Comment by ivan** [comment]
Right, if something is a stylesheet or `<img src="...">` or another thing wpull treats as a page requisite, it *is* grabbed from other domains even with `--no-offsite-links`.  But not `<a href="...">`s.

I don't think there's an easy way to limit it to a wildcarded subdomain.  Feel free to file an issue, but I probably won't have time to work on it unless I get a fairly clean PR.

This might be possible to implement with a new option and a modified `def accept_url` in `wpull_hooks.py`; hopefully a forked wpull 1.2.3 is not necessary.

Closing because the behavior you observed is expected (despite being a little confusing).  Let me know if it doesn't match what I described.

**Comment by WAZAAAAA0** [comment]
was wildcard support ever added? If not, I second the notion that a way to include all sub-domains and exclude external domains would be great

it's doable in HTTrack by setting the `Scan Rules` to something like this:
`-* +example.com/* +*.example.com/*`
