### ISSUE TITLE
(enhancement idea) Installer packages with traditional app files (.exe / .app)

### ISSUE THREAD

**Issue by ethus3h** [ludios/grab-site#23]
For OS X and Windows, it seems like it would make sense to package grab-site as an installer (.pkg for OS X, .msi for Windows) with a wrapper to easily launch grab-site (server and dashboard) from the Applications folder or Dock (OS X) or the Start screen, Task bar, or Desktop (Windows). This would seem to make it more user friendly, since I think a lot of computer users probably aren't into working with the command line, necessarily.

This issue isn't relevant to me really, just something that seems like it might make the program more accessible to a wider audience.

**Comment by ivan** [comment]
Windows support isn't here yet due to psutil and console output issues.  grab-site also currently requires that users be able to run things from the command line, edit control files, and edit environmental variables.  Doing these installers would be not-fun and wouldn't expand the audience much at the moment.  Right now grab-site is an advanced tool and I don't think I want to support the audience that can't `pip3`.  Perhaps something for the distant future.

**Comment by ethus3h** [comment]
Ah, oh well. Was just an idea :)
