### ISSUE TITLE
Add youtube-dl support

### ISSUE THREAD

**Issue by rwoodpecker** [ludios/grab-site#37]
I hope this isn't beyond the scope of this project - but the support for youtube-dl in AB is extremely useful for a range of media sites that are otherwise unusable with grab-site and the like. Would this be possible to implement?

Thanks!

**Comment by ivan** [comment]
I'm not completely against adding `--youtube-dl` to match wpull's `--youtube-dl`, but the whole business of putting YouTube (and other sites') videos in WARC files confuses me.  Can you tell me:

1) How you play back these videos, or how you plan to play them back? (i.e. which WARC player or extractor plans to support this, or how would you do it today?)

2) Given that YouTube serves unmuxed videos, whether you want to archive the original unmuxed audio and video files, or the video after being muxed by ffmpeg?  This is important because the unmuxed versions are the "originals" but are relatively useless until muxed.  Also because muxing will require users to install ffmpeg.

2b) If the answer to '2)' is "unmuxed videos", how do you play back unmuxed videos? (Is the plan to have a WARC player that discovers youtube-dl responses in the WARCs, runs ffmpeg to mux them, and streams the output?)

The general nature of my concern is that `--youtube-dl` will produce giant WARCs from which no one knows how to play things, but I could be wrong, I don't know much about the WARC playback tools out there.

**Comment by rwoodpecker** [comment]
I completely agree with all those criticisms. It's not a good way to archive youtube videos, quite messy, ends with nasty transcodes. 

My interest in youtube-dl doesn't lie in youtube itself, but websites like soundcloud that serve you a .mp3 or .mp4 or whatever file - wpull doesn't seem to handle these without a direct download link while youtube-dl can of course get them.

I'm going to close this and look into it a bit further, but I feel if the files youtube-dl gets don't integrate with the saves that wpull does, it's probably a bit pointless

**Comment by ivan** [comment]
Try the new `--wpull-args` if you want `--youtube-dl`; make sure you have ffmpeg installed or uninstalled depending on how you want youtube-dl to behave on youtube.com; soundcloud should be less problematic

**Comment by rwoodpecker** [comment]
Amazing. Works a charm :+1: Thanks.
